# Generated by Django 5.0 on 2023-12-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_recipe_curr_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='curr_user',
        ),
    ]
