# Generated by Django 5.0 on 2023-12-16 13:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_remove_recipe_curr_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('recipe_name', 'user')},
        ),
    ]
