# Generated by Django 5.0 on 2023-12-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_alter_recipe_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set(),
        ),
    ]
