# Generated by Django 5.0 on 2023-12-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0010_alter_recipe_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
    ]
