# Generated by Django 5.0 on 2023-12-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0012_recipe_likes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
