# Generated by Django 5.0 on 2023-12-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0013_remove_recipe_likes_delete_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
