# Generated by Django 5.0 on 2023-12-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0015_remove_recipe_recipe_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
